version: "3.9"
services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - frontend

  frontend:
    build: ./app/frontend
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/frontend
    environment:
      - BACKEND_URL=http://backend:8000/upload/